name: Deploy Github Page
on:
  push:
    branches:
      - master
      - alpinejs
jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Run
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # root directory if your site is already built