jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "Add your build commands here"

  deploy:
    needs: build
    permissions:
      pages: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploying Run
        id: deployment
        uses: actions/deploy-pages@v4
